name: Validate

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Lint Go
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: v1.61.0
          args: --timeout 3m0s
